   name: CI
   on:
     push:
       branches:
         - main
     pull_request:
       branches:
         - main

   jobs:
     build-deploy:

       runs-on: ubuntu-latest

       steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: Set up JDK
         uses: actions/setup-java@v2
         with:
           distribution: 'adopt'
           java-version: '17'

       - name: Cache Maven packages
         uses: actions/cache@v2
         with:
           path: ~/.m2/repository
           key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
           restore-keys: |
             ${{ runner.os }}-maven-

       - name: Build with Maven
         run: mvn clean install

       - name: Run tests
         run: mvn test
         
       - name: build the docker image
         uses: docker/build-push-action@v4
         with:
            context: .
            dockerfile: Dockerfile
            push: false
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/recipe:v1.0.0

       - name: login to docker hub
         uses: docker/login-action@v1
         with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            
       - name: push image  to docker hub
         uses: docker/build-push-action@v4
         with:
            context: .
            dockerfile: Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/recipe:v1.0.0  
